export const INDIAN_STATE_OPTIONS = [
  "Andhra Pradesh",
  "Arunachal Pradesh",
  "Assam",
  "Bihar",
  "Chhattisgarh",
  "Goa",
  "Gujarat",
  "Haryana",
  "Himachal Pradesh",
  "Jharkhand",
  "Karnataka",
  "Kerala",
  "Madhya Pradesh",
  "Maharashtra",
  "Manipur",
  "Meghalaya",
  "Mizoram",
  "Nagaland",
  "Odisha",
  "Punjab",
  "Rajasthan",
  "Sikkim",
  "Tamil Nadu",
  "Telangana",
  "Tripura",
  "Uttar Pradesh",
  "Uttarakhand",
  "West Bengal",
  "Andaman and Nicobar Islands",
  "Chandigarh",
  "Dadra and Nagar Haveli and Daman and Diu",
  "Delhi",
  "Jammu and Kashmir",
  "Ladakh",
  "Lakshadweep",
  "Puducherry",
] as const;

export const INDIAN_CITY_OPTIONS: Record<string, readonly string[]> = {
  "Andhra Pradesh": [
    "Visakhapatnam",
    "Vijayawada",
    "Guntur",
    "Tirupati",
    "Kakinada",
    "Rajamahendravaram",
    "Nellore",
    "Ongole",
    "Kurnool",
    "Anantapur",
    "Kadapa",
    "Eluru",
    "Machilipatnam",
    "Nandyal",
    "Srikakulam",
    "Vizianagaram",
  ],

  "Arunachal Pradesh": [
    "Itanagar",
    "Naharlagun",
    "Pasighat",
    "Tawang",
    "Bomdila",
    "Ziro",
    "Tezu",
    "Roing",
  ],

  Assam: [
    "Guwahati",
    "Dibrugarh",
    "Silchar",
    "Jorhat",
    "Nagaon",
    "Tezpur",
    "Tinsukia",
    "Sivasagar",
    "Barpeta",
    "Dhubri",
    "Karimganj",
    "Bongaigaon",
  ],

  Bihar: [
    "Patna",
    "Gaya",
    "Bhagalpur",
    "Muzaffarpur",
    "Purnia",
    "Darbhanga",
    "Begusarai",
    "Arrah",
    "Bihar Sharif",
    "Katihar",
    "Sasaram",
    "Motihari",
  ],

  Chhattisgarh: [
    "Raipur",
    "Bhilai",
    "Bilaspur",
    "Korba",
    "Durg",
    "Rajnandgaon",
    "Jagdalpur",
    "Ambikapur",
    "Raigarh",
    "Mahasamund",
  ],

  Goa: [
    "Panaji",
    "Margao",
    "Vasco da Gama",
    "Mapusa",
    "Ponda",
    "Bicholim",
  ],

  Gujarat: [
    "Ahmedabad",
    "Surat",
    "Vadodara",
    "Rajkot",
    "Bhavnagar",
    "Jamnagar",
    "Junagadh",
    "Gandhinagar",
    "Anand",
    "Bharuch",
    "Mehsana",
    "Morbi",
    "Navsari",
    "Valsad",
    "Porbandar",
    "Patan",
  ],

  Haryana: [
    "Gurugram",
    "Faridabad",
    "Panipat",
    "Ambala",
    "Hisar",
    "Karnal",
    "Rohtak",
    "Sonipat",
    "Yamunanagar",
    "Bhiwani",
    "Sirsa",
    "Jind",
  ],

  "Himachal Pradesh": [
    "Shimla",
    "Mandi",
    "Dharamshala",
    "Solan",
    "Kullu",
    "Una",
    "Hamirpur",
    "Bilaspur",
    "Chamba",
    "Nahan",
  ],

  Jharkhand: [
    "Ranchi",
    "Jamshedpur",
    "Dhanbad",
    "Bokaro Steel City",
    "Deoghar",
    "Hazaribagh",
    "Giridih",
    "Dumka",
    "Ramgarh",
    "Chaibasa",
  ],

  Karnataka: [
    "Bengaluru",
    "Mysuru",
    "Mangaluru",
    "Hubballi",
    "Belagavi",
    "Davanagere",
    "Ballari",
    "Kalaburagi",
    "Shivamogga",
    "Tumakuru",
    "Udupi",
    "Bidar",
    "Raichur",
    "Vijayapura",
    "Hassan",
  ],

  Kerala: [
    "Thiruvananthapuram",
    "Kochi",
    "Kozhikode",
    "Thrissur",
    "Kollam",
    "Kannur",
    "Alappuzha",
    "Kottayam",
    "Palakkad",
    "Malappuram",
    "Pathanamthitta",
    "Idukki",
    "Kasaragod",
    "Wayanad",
  ],

  "Madhya Pradesh": [
    "Bhopal",
    "Indore",
    "Gwalior",
    "Jabalpur",
    "Ujjain",
    "Sagar",
    "Rewa",
    "Satna",
    "Dewas",
    "Ratlam",
    "Chhindwara",
    "Singrauli",
  ],

  Maharashtra: [
    "Mumbai",
    "Pune",
    "Nagpur",
    "Nashik",
    "Thane",
    "Aurangabad",
    "Kolhapur",
    "Solapur",
    "Amravati",
    "Akola",
    "Latur",
    "Nanded",
    "Ahmednagar",
    "Jalgaon",
    "Satara",
    "Ratnagiri",
    "Sangli",
    "Chandrapur",
  ],

  Manipur: [
    "Imphal",
    "Thoubal",
    "Bishnupur",
    "Kakching",
    "Ukhrul",
    "Churachandpur",
  ],

  Meghalaya: [
    "Shillong",
    "Tura",
    "Nongpoh",
    "Jowai",
    "Baghmara",
    "Williamnagar",
  ],

  Mizoram: [
    "Aizawl",
    "Lunglei",
    "Champhai",
    "Serchhip",
    "Kolasib",
    "Saiha",
  ],

  Nagaland: [
    "Kohima",
    "Dimapur",
    "Mokokchung",
    "Tuensang",
    "Wokha",
    "Zunheboto",
    "Phek",
  ],

  Odisha: [
    "Bhubaneswar",
    "Cuttack",
    "Rourkela",
    "Sambalpur",
    "Berhampur",
    "Balasore",
    "Puri",
    "Bhadrak",
    "Baripada",
    "Jharsuguda",
    "Koraput",
  ],

  Punjab: [
    "Ludhiana",
    "Amritsar",
    "Jalandhar",
    "Patiala",
    "Bathinda",
    "Mohali",
    "Hoshiarpur",
    "Pathankot",
    "Moga",
    "Firozpur",
  ],

  Rajasthan: [
    "Jaipur",
    "Jodhpur",
    "Udaipur",
    "Kota",
    "Ajmer",
    "Bikaner",
    "Alwar",
    "Bharatpur",
    "Pali",
    "Sikar",
    "Barmer",
    "Jaisalmer",
    "Bhilwara",
    "Tonk",
  ],

  Sikkim: [
    "Gangtok",
    "Namchi",
    "Mangan",
    "Gyalshing",
    "Pakyong",
    "Singtam",
  ],

  "Tamil Nadu": [
    "Chennai",
    "Coimbatore",
    "Madurai",
    "Salem",
    "Tiruchirappalli",
    "Tirunelveli",
    "Erode",
    "Vellore",
    "Thoothukudi",
    "Dindigul",
    "Tiruppur",
    "Thanjavur",
    "Karur",
    "Namakkal",
    "Kanchipuram",
    "Cuddalore",
    "Nagapattinam",
    "Villupuram",
    "Tenkasi",
    "Virudhunagar",
    "Sivakasi",
    "Hosur",
    "Nagercoil",
  ],

  Telangana: [
    "Hyderabad",
    "Warangal",
    "Nizamabad",
    "Khammam",
    "Karimnagar",
    "Ramagundam",
    "Mahabubnagar",
    "Adilabad",
    "Sangareddy",
    "Siddipet",
    "Nalgonda",
    "Kamareddy",
  ],

  Tripura: [
    "Agartala",
    "Dharmanagar",
    "Udaipur",
    "Kailasahar",
    "Belonia",
    "Khowai",
  ],

  "Uttar Pradesh": [
    "Lucknow",
    "Kanpur",
    "Varanasi",
    "Agra",
    "Prayagraj",
    "Ghaziabad",
    "Noida",
    "Meerut",
    "Aligarh",
    "Bareilly",
    "Moradabad",
    "Gorakhpur",
    "Ayodhya",
    "Jhansi",
    "Mathura",
    "Saharanpur",
    "Muzaffarnagar",
    "Firozabad",
  ],

  Uttarakhand: [
    "Dehradun",
    "Haridwar",
    "Roorkee",
    "Haldwani",
    "Rudrapur",
    "Kashipur",
    "Nainital",
    "Pithoragarh",
    "Almora",
  ],

  "West Bengal": [
    "Kolkata",
    "Howrah",
    "Durgapur",
    "Siliguri",
    "Asansol",
    "Kharagpur",
    "Malda",
    "Berhampore",
    "Darjeeling",
    "Haldia",
  ],

  "Andaman and Nicobar Islands": [
    "Port Blair",
    "Diglipur",
    "Mayabunder",
  ],

  Chandigarh: ["Chandigarh"],

  "Dadra and Nagar Haveli and Daman and Diu": [
    "Silvassa",
    "Daman",
    "Diu",
  ],

  Delhi: [
    "New Delhi",
    "Dwarka",
    "Rohini",
    "Saket",
    "Karol Bagh",
    "Janakpuri",
    "Pitampura",
    "Shahdara",
    "Narela",
    "Laxmi Nagar",
  ],

  "Jammu and Kashmir": [
    "Srinagar",
    "Jammu",
    "Anantnag",
    "Baramulla",
    "Pulwama",
    "Kupwara",
    "Kathua",
    "Udhampur",
  ],

  Ladakh: [
    "Leh",
    "Kargil",
    "Diskit",
  ],

  Lakshadweep: [
    "Kavaratti",
    "Agatti",
    "Amini",
    "Andrott",
  ],

  Puducherry: [
    "Puducherry",
    "Karaikal",
    "Mahe",
    "Yanam",
  ],
};

export const getCityItemsForState = (state?: string) =>
  (INDIAN_CITY_OPTIONS[state || ""] || []).map((city) => ({
    label: city,
    value: city,
  }));